name: Copila y genera PDF
on: 
  push

jobs: 
  compilacion: 
    runs-on: ubuntu-latest
    steps:
      - name: Copia local
        uses: actions/checkout@4.2.2
      
      - name: Instalar .NET en el runner
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Instalar dependencia
        run: dotnet restore

      - name: compilar
        run: dotnet build --no-restore

  create-pdf:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@ve
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
